modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="golemysm_link"
version="1.0.0"
displayName="Golem YSM Link"
authors="Ai_Run"
description='''YSM models for Modular Golems humanoid golems through Touhou Little Maid.'''

[[dependencies.golemysm_link]]
modId="forge"
mandatory=true
versionRange="[47.4.18,48)"
ordering="NONE"
side="BOTH"

[[dependencies.golemysm_link]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"

[[dependencies.golemysm_link]]
modId="modulargolems"
mandatory=true
versionRange="[2.6.45,2.7.4]"
ordering="AFTER"
side="BOTH"

[[dependencies.golemysm_link]]
modId="touhou_little_maid"
mandatory=true
versionRange="[1.4.0-forge+mc1.20.1,1.5.3-forge+mc1.20.1]"
ordering="AFTER"
side="BOTH"

[[dependencies.golemysm_link]]
modId="yes_steve_model"
mandatory=true
versionRange="[2.6.5-forge+mc1.20.1]"
ordering="AFTER"
side="BOTH"
